(() => {
  const storage = {
    dollar: {
      title: "Dollar",
      link: "https://en.wikipedia.org/wiki/Dollar",
      text: [`On 15 January 1520, the Czech Kingdom of Bohemia began minting coins from silver mined locally in Joachimsthal (Czech Jáchymov) and marked on reverse with the Czech lion. The coins were called joachimsthaler, which became shortened in common usage to thaler or taler. The German name "Joachimsthal" literally means "Joachim's valley" or "Joachim's dale". This name found its way into other languages: Czech tolar, Hungarian tallér, Danish and Norwegian (rigs)daler, Swedish (riks)daler, Icelandic dalur, Dutch (rijks)daalder or daler, Ethiopian ታላሪ ("talari"), Italian tallero, Greek τάλληρον, τάλιρο, tàlleron, tàliro, Polish talar, Persian dare, as well as – via Dutch – into English as dollar.`,
        `A later Dutch coin also depicting a lion was called the leeuwendaler or leeuwendaalder, literally 'lion daler'. The Dutch Republic produced these coins to accommodate its booming international trade. The leeuwendaler circulated throughout the Middle East and was imitated in several German and Italian cities. This coin was also popular in the Dutch East Indies and in the Dutch New Netherland Colony (New York). It was in circulation throughout the Thirteen Colonies during the 17th and early 18th centuries and was popularly known as "lion (or lyon) dollar".[2][3] The currencies of Romania and Bulgaria are, to this day, 'lion' (leu/leva). The modern American-English pronunciation of dollar is still remarkably close to the 17th century Dutch pronunciation of daler.[4] Some well-worn examples circulating in the Colonies were known as "dog dollars".`,
        `Spanish pesos – having the same weight and shape – came to be known as Spanish dollars.[4][6] By the mid-18th century, the lion dollar had been replaced by Spanish dollar, the famous "pieces of eight", which were distributed widely in the Spanish colonies in the New World and in the Philippines.`
      ]
    },
    euro: {
      title: "Euro",
      link: "https://en.wikipedia.org/wiki/Euro",
      text: [`The euro (sign: €; code: EUR) is the official currency of the eurozone, which consists of 19 of the 28 member states of the European Union: Austria, Belgium, Cyprus, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Latvia, Lithuania, Luxembourg, Malta, the Netherlands, Portugal, Slovakia, Slovenia, and Spain.`,
      `The currency is also officially used by the institutions of the European Union and four other European countries, as well as unilaterally by two others, and is consequently used daily by some 337 million Europeans as of 2015.[5] Outside of Europe, a number of overseas territories of EU members also use the euro as their currency. Additionally, 210 million people worldwide as of 2013 use currencies pegged to the euro.`,
      `The euro is the second largest reserve currency as well as the second most traded currency in the world after the United States dollar.[6][7][8] As of January 2017, with more than €1,109,000,000,000 in circulation, the euro has one of the highest combined values of banknotes and coins in circulation in the world, having surpassed the U.S. dollar at one point.`,
      `The name euro was officially adopted on 16 December 1995 in Madrid.[10] The euro was introduced to world financial markets as an accounting currency on 1 January 1999, replacing the former European Currency Unit (ECU) at a ratio of 1:1 (US$1.1743). Physical euro coins and banknotes entered into circulation on 1 January 2002, making it the day-to-day operating currency of its original members, and by May 2002 had completely replaced the former currencies.[11] While the euro dropped subsequently to US$0.8252 within two years (26 October 2000), it has traded above the U.S. dollar since the end of 2002, peaking at US$1.6038 on 18 July 2008.[12] Since late 2009, the euro has been immersed in the European sovereign-debt crisis which has led to the creation of the European Financial Stability Facility as well as other reforms aimed at stabilising the currency. In July 2012, the euro fell below US$1.21 for the first time in two years, following concerns raised over Greek debt and Spain's troubled banking sector.[13] As of June 2017, the euro–dollar exchange rate stands at ~ US$1.13.`]
    },
    yen: {
      title: "Japanese yen",
      link: "https://en.wikipedia.org/wiki/Japanese_yen",
      text: [`The yen (Japanese: 円 Hepburn: en, symbol: ¥; code: JPY) is the official currency of Japan. It is the third most traded currency in the foreign exchange market after the United States dollar and the euro.[4] It is also widely used as a reserve currency after the U.S. dollar, the euro, and the pound sterling.`,
      `The concept of the yen was a component of the Meiji government's modernization program of Japan's economy; which postulated the pursuit of a uniform currency throughout the country modeled after the European decimal currency system. Before the Meiji Restoration, Japan's feudal fiefs all issued their own money, hansatsu, in an array of incompatible denominations. The New Currency Act of 1871 did away with these and established the yen, which was defined as 1.5 g (0.048 troy ounces) of gold, or 24.26 g (0.780 troy ounces) of silver, as the new decimal currency. The former han (fiefs) became prefectures and their mints private chartered banks, which initially retained the right to print money. To bring an end to this situation the Bank of Japan was founded in 1882 and given a monopoly on controlling the money supply.`,
      `Following World War II the yen lost much of its prewar value. To stabilize the Japanese economy the exchange rate of the yen was fixed at ¥360 per $1 as part of the Bretton Woods system. When that system was abandoned in 1971, the yen became undervalued and was allowed to float. The yen had appreciated to a peak of ¥271 per $1 in 1973, then underwent periods of depreciation and appreciation due to the 1973 oil crisis, arriving at a value of ¥227 per $1 by 1980.`,
      `Since 1973, the Japanese government has maintained a policy of currency intervention, and the yen is therefore under a “dirty float” regime. This intervention continues until today. The Japanese government focuses on a competitive export market, and tries to ensure a low yen value through a trade surplus. The Plaza Accord of 1985 temporarily changed this situation from its average of ¥239 per US$1 in 1985 to ¥128 in 1988 and led to a peak value of ¥80 against the U.S. dollar in 1995, effectively increasing the value of Japan’s GDP to almost that of the United States. Since that time, however, the yen has greatly decreased in value. The Bank of Japan maintains a policy of zero to near-zero interest rates and the Japanese government has an extreme anti-inflation policy.`]
    },
    rupee: {
      title: "Rupee",
      link: "https://en.wikipedia.org/wiki/Rupee",
      text: [`The rupee is the common name for the currencies of India, Pakistan, Indonesia, Maldives, Mauritius, Nepal, Seychelles, Sri Lanka, and formerly those of Afghanistan, Tibet, Burma and British East Africa, German East Africa and Trucial States.`,
      `In the Maldives, the unit of currency is known as the rufiyah, which is a cognate of the Sanskrit rupya. The Indian rupees (₹) and Pakistani rupees (₨) are subdivided into one hundred paise (singular paisa) or pice. The Mauritian and Sri Lankan rupees subdivide into 100 cents. The Nepalese rupee subdivides into one hundred paisas (both singular and double) or four sukas or two mohors.`,
      `The Indian rupee was first introduced, issued and termed as rupiya, the silver coin, by Sher Shah Suri (1540–1545), continued by the Mughal rulers.[5] The history of the rupee traces back to Ancient India circa 3rd century BC. Ancient India was one of the earliest issuers of coins in the world,[6] along with the Lydian staters, several other Middle Eastern coinages and the Chinese wen. The term is from rūpya, a Sanskrit term for silver coin,[7] from Sanskrit rūpá, beautiful form.`,
      `Both the Kabuli rupee and the Kandahari rupee were used as currency in Afghanistan prior to 1891, when they were standardized as the Afghan rupee. The Afghan rupee, which was subdivided into 60 paisas, was replaced by the Afghan afghani in 1925.`]
    },
    sheqel: {
      title: "Sheqel",
      link: "https://en.wikipedia.org/wiki/Shekel",
      text: [`Shekel (Akkadian: šiqlu or siqlu; Hebrew: שקל‎‎, pl. shekels or sheqalim) is any of several ancient units of weight or of currency. Initially, it may have referred to a weight of barley. This shekel was about 180 grains (11 grams or .35 troy ounces). Since 1980, the shekel has been the main monetary unit in Israel.`,
      `The earliest shekels were a unit of weight, used as other units such as grams and troy ounces for trading before the advent of coins. The shekel was common among western Semitic peoples. Moabites, Edomites, and Phoenicians used the shekel, although proper coinage developed very late. Carthaginian coinage was based on the shekel and may have preceded its home town of Tyre in issuing proper coins.`,
      `Coins were used and may have been invented by the early Anatolian traders who stamped their marks to avoid weighing each time used. Herodotus states that the first coinage was issued by Croesus, King of Lydia, spreading to the golden Daric (worth 20 sigloi or shekel),[4] issued by the Persian Empire and the silver Athenian obol and drachma. Early coins were money stamped with an official seal to certify their weight. Silver ingots, some with markings were issued. Later authorities decided who designed coins.`,
      `As with many ancient units, the shekel had a variety of values depending on era, government and region; weights between 7[6] and 17 grams and values of 11,[7] 14, and 17 grams are common. When used to pay laborers, recorded wages in the ancient world range widely. The Code of Hammurabi (circa 1800 BC) sets the value of unskilled labor at approximately ten shekels per year of work.[8] Later, records within the Persian Empire (539-333 BC) give ranges from a minimum of two shekels per month for unskilled labor, to as high as seven to ten shekels per month in some records.[9] A survival wage for an urban household during the Persian period would require at least 22 shekels of income per year.`,
      `Exodus 30:24 notes that the measures of the ingredients for the holy anointing oil were to be calculated using the Shekel of the Sanctuary (see also Exodus 38:24–26, and similarly at Numbers 3:47 for payment for the redemption of 273 first-born males [10] and at Numbers 7:12–88 for the offerings of the leaders of the tribes of Israel), suggesting that there were other common measures of shekel in use, or at least that the Temple authorities defined a standard for the shekel to be used for Temple purposes.`]
    },
    bitcoin: {
      title: "Bitcoin",
      link: "https://en.wikipedia.org/wiki/Bitcoin",
      text: [`Bitcoin is a cryptocurrency and a digital payment system[13]:3 invented by an unknown programmer, or a group of programmers, under the name Satoshi Nakamoto.[14] It was released as open-source software in 2009.`,
      `The system is peer-to-peer, and transactions take place between users directly, without an intermediary.[13]:4 These transactions are verified by network nodes and recorded in a public distributed ledger called a blockchain. Since the system works without a central repository or single administrator, bitcoin is called the first decentralized digital currency.`,
      `Besides being created as a reward for mining, bitcoin can be exchanged for other currencies,[17] products, and services in legal or black markets.`,
      `As of February 2015, over 100,000 merchants and vendors accepted bitcoin as payment.[20] According to research produced by Cambridge University in 2017, there are 2.9 to 5.8 million unique users using a cryptocurrency wallet, most of them using bitcoin.`,
      `The unit of account of the bitcoin system is bitcoin. As of 2014, symbols used to represent bitcoin are BTC,[note 1] XBT,[note 2] and ₿ (U+20BF, BitcoinSign.svg).[note 3][33]:2 Small amounts of bitcoin used as alternative units are millibitcoin (mBTC),[1] microbitcoin (µBTC, sometimes referred to as bit), and satoshi. Named in homage to bitcoin's creator, a satoshi is the smallest amount within bitcoin representing 0.00000001 bitcoin, one hundred millionth of a bitcoin.[9] A millibitcoin equals to 0.001 bitcoin, one thousandth of a bitcoin.[34] One microbitcoin equals to 0.000001 bitcoin, one millionth of a bitcoin.`]
    }
  }
})()
